- src/drizzle/patterns/data-types/table-with-category-column.hbs
- Data was appearing under incorrect headers
To Check:
- Ensure that data in the stacked bar charts is appearing in its correct order
- Turn off JS and ensure that the data in the stacked bar chart tables is appearing in its correct order.
> fix: reverses data display for the stacked bar chart tables

- gatsby-config.js
- src/components/layout.js
- src/pages/index.js
- src/scss/_tools.typography.scss
- src/scss/base.scss
Add font links to head using [react helmet](https://www.gatsbyjs.org/docs/custom-html/#inserting-html-into-the-head) (best choice based on Gatsby docs and stackoverflow research). 
Add typography mixins and classes.
1. Go to localhost:8000, open dev tools, make sure the fonts are listed in the `<head>`:
2. You can also update the `base.scss` file to include `font-family: 'Yellowtail';` or `font-family: 'Whitney SSm A';` on the `<body>` to see the font working
1. Check that the text styles on the index page (localhost:8000) work and match [the design](https://sparkbox.invisionapp.com/d/main#/console/17598448/365064738/inspect)
> feat: font styles

- src/components/layout.js
- src/js/safe-focus.js
- src/scss/_generic.focus.scss
- src/scss/_tools.mixins.general.scss
- src/scss/base.scss
Taken from [AES commit](https://github.com/sparkbox/aes-design-system/commit/ec9994cf0ffbb256b5c939c82393cbc3474aeb69) and modified to serve our purpose. Testing: tab through and make sure you can see the focus state
> DSS-60 feat: safe focus

- gatsby-config.js
- package-lock.json
- package.json
Add Google tag manager. Gatsby handles this with a plugin instead of hard coded in the head.
To test:
1. In `gatsby-config.js`, change `includeInDevelopment` to `true`
2. Download the Google Tag Assistant extension in Google Chrome
3. Open Dev Tools > Network tab
4. Reload the page. You should see a name starting with `collect`. This is the tag manager. To confirm you can hover over it and make sure it says google tag manager later in the name
> feat: google tag manager

- src/scss/_components.typography.scss
- src/sections/section-5.mdx
Adds additional gradient link style and transition effect. Also adds the link to the CSV file as [the card](https://sparkbox.atlassian.net/secure/RapidBoard.jspa?rapidView=61&projectKey=DSS&modal=detail&selectedIssue=DSS-67) originally requested.
Here's my logic on adding this link as HTML in the MDX file. I did some research to see if I could add classes to MDX elements, and found that I can with [a plugin](https://github.com/martypdx/rehype-add-classes), however, it will add the class to every single one of those elements.
So to add a class to these "learn more" links at the end of the page means adding that class to all the links on the page, which means overriding something with HTML anyway. There are fewer of these links than other links on the page, so I chose to customize these …
> DSS-67 feat: learn more link style, add link to CSV download

- src/components/content-block.js
- src/pages/404.js
- src/pages/chart.mdx
- src/scss/_components.404.scss
- src/scss/_objects.layout.flexbox.scss
- src/scss/base.scss
Add custom 404 page
Per [Gatsby.js docs](https://www.gatsbyjs.org/docs/add-404-page/), "when developing, Gatsby adds a default 404 page that overrides your custom 404 page. But you can still preview your 404 page by clicking “Preview custom 404 page” to verify that it’s working as expected."
> DSS-8 feat: custom 404 page

- src/components/diagram-table-block.js
- src/components/useful-feature-list.js
- src/scss/_components.feature-list.scss
- src/scss/base.scss
- src/sections/section-2.mdx
Aligns designer and dev lists of useful features. Not sure about the naming on this one, let me know if you have suggestions.
(Note: Zastrow suggested we add the 3d shape graphics in a different PR)
> DSS-76 useful features list component

- src/components/diagram-4a.js
Thinking this may have been cased by copying content over from Google Docs/Sheets. I found these weird little symbols (shown below) when I looked at the chart file in VS Code, so I removed those and then the LSEP character was gone in Edge. ¯\_(ツ)_/¯
> DSS-81 fix: edge character bug

- src/components/top-tools-list.js
- src/scss/_components.feature-list.scss
- src/sections/section-2.mdx
I ended up keeping the word "responses" next to each list item because the numbers didn't make sense on their own.
> DSS-87 feat: top tools comparison list components, styles

- src/scss/_components.typography.scss
- src/sections/section-5.mdx
Needs a design eye. The gradient underline wraps now, but when the text wraps it starts again at blue, whereas the underline stays at whatever point it is in it's independent gradient. Meaning that the colors don't align when it wraps. Not sure what the best solution is for this.
> DSS-80 fix: link underline bug

- src/components/diagram-3a.js
- src/scss/_components.diagram.scss
The work in this PR improves accessibility by displaying the table version of all charts when a user tabs through the site.
Run the project locally `gatsby develop`
Go to `localhost:8000`
Scrolling through the site at small and large screen sizes, you should not see any changes. Everything should look exactly the same. At small screen sizes you should see bar charts and tables. At large screen sizes you should see bar and cylinder charts.
Previously when tabbing through content while using a screen reader, the charts were skipped over. Now when tabbing through the site all charts should be hidden while their table counterpart is displayed.
The presentation of content within the table which features the scale of 1 to 5 has been improved by adding `aria-labels` to the table column headings …
> DSS-90 : Improve accessibility of charts / tables

- src/components/diagram-2a.js
- src/components/diagram-3a.js
- src/components/diagram-3b.js
- src/components/diagram-3c.js
- src/components/diagram-4a.js
- src/components/diagram-4b.js
Uses `aria-hidden` to hide decorative pipe from screen readers.
> DSS-97 fix: hide pipe decoration from screen readers

- src/components/top-tools-list.js
- src/components/useful-feature-list.js
Updated header tags to eliminate jumps from `<h2>` to `<h4>`.
Spin up your local dev environment with `gatsby develop` and go to `http://localhost:8000/`
There are two ways you can test this PR:
1) Activate VoiceOver. `Command + Fn + F5`
Press `Option + Control + U` to open up the web item rotor. Use the left and right arrow keys to find the `Headings Menu`. Scan through the headings to confirm they are in semantic order with no heading levels skipped over.
2) Go to `http://localhost:8000/` in Chrome.
Open `Developer Tools`
Go to the `Audits` tab
Under `Audits` select `Accessibility`
Run the audit.
There should not be any heading structure errors.
> DSS-104 : update header tags for proper semantics and improved accessibility

- src/components/table-of-contents.js
- src/scss/_components.table-of-contents.scss
- src/scss/_components.typography.scss
It appears that Safari has issues recalculating `vw` units upon zoom. The size of the `Table of Contents` header has been reduced a touch to prevent horizontal scroll when the browser is zoomed in to 200%. 
After running `gatsby develop` to start up a local dev environment, go to `localhost:8000` in Safari. Using the `Command and +` keys zoom out to 200%. Confirm there is no horizontal scroll. Note that if you zoom past 200%, you will get the horizontal scroll. 200% is the threshold for passing [WCAG Success Criterion 1.4.4](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html).
Test in additional browsers to confirm no new bugs have been introduced.
> DSS-100 : Adjust vw size of the Table of Contents header to prevent horizontal scroll at 200%

- src/components/form.js
Before, the form would let you hit "submit" with nothing in the input and give you a "yay you signed up" message. Now it says "invalid" when you try to submit a blank form.
> DSS-114 fix: add validation to email, wont submit blank input

- src/scss/_components.respondents.scss
- src/scss/_components.shape.cube.scss
- src/scss/_components.shape.diamond.scss
- src/scss/_components.shape.dodecahedron.scss
- src/scss/_components.shape.pyramid.scss
Respondent shapes were not rendering correctly in Edge.
It was discovered that the `calc` function does not work as expected when used in `transforms` with the `Z axis`. The codebase was refactored to explicitly declare `z axis` values thus eliminating the use of the `calc` function.
Go to http://localhost:8000 in multiple browsers to confirm the shapes render correctly.
> DSS-88 : refactor respondent shapes to render in all browsers

- src/components/diagram-2a.js
- src/components/diagram-3b.js
- src/components/diagram-3c.js
- src/components/diagram-respondents.js
- src/scss/_components.diagram.chart.scss
[DSS-115](https://sparkbox.atlassian.net/browse/DSS-115) shows the original validation report. Below is the new report. A few notes:
* The first error about `fetch` is not something I think we have control over, I think that's Gatsby 🤔 
* Seems like we're ok for all those warnings, but if reviewer thinks otherwise let's look into them!
Test in a few browsers that the platform on the charts and the respondents shapes are still working correctly:
[screencapture-validator-w3-org-nu-2019-07-19-09_56_30.pdf](https://github.com/sparkbox/designsystemssurvey/files/3411366/screencapture-validator-w3-org-nu-2019-07-19-09_56_30.pdf)
> DSS-115 validation

- src/sections/section-4.mdx
Spin up your local development environment by running `gatsby develop`
Go to http://localhost:8000/
Scroll or in the table of contents, click on number 4 to go to the section titled `Creating a Successful Design System`
> DSS-117 : remove charts and update copy for section 4

- src/scss/_components.chart.row-chart.scss
Fixes a problem where 61% looked different on different rows of the horizontal graph. Bonus: refactor of percentage hover on small screen sizes so that percentage doesn't overlap label.
> fix: numbers on chart being visually uneven, refactor: percents on hover

- src/scss/_components.diagram.chart.scss
- src/scss/_components.respondents.scss
- src/scss/_components.table-of-contents.scss
Reverts some CSS changes from #217 to remove the horizontal scrolling in Firefox.
> DSS-119 fix: firefox horizontal scroll caused by chart platform

- src/sections/section-5.mdx
This removes the duplicate paragraph at the bottom of the site and fixes a typo.
To validate:
- Run `gatsby develop`
- Go to http://localhost:8000/
- Scroll to Section 5 and make sure that the paragraph is typo free and no longer duplicated.
> fix: remove duplicate paragraph in section 5

- src/components/layout.js
issue:
- Twitter Cards shared from the site do not render previews or pass
twitter card validation.
fix:
From what I gather, adding a og:title could resolve the error.
Validation instructions:
pull down branch.
run `npm run develop`
inspect `<head>` and observe added `og:title` meta tag added.
I don't think we can fully test that this solution works until it is deployed at a url for which we can utilize https://cards-dev.twitter.com/validator
> feat: Add og:title to site metaData

- static/_redirects
[Netlify used to force redirects, but they had a bug](https://community.netlify.com/t/changed-behavior-in-redirects/10084). Now we have to manually force redirect, which is what's happening in this PR
**To test:**
- Go to the deploy preview: https://5e78cbda4358da0007dfbfe0--angry-mirzakhani-365cef.netlify.com/
- Make sure that it redirects you to https://5e78cbda4358da0007dfbfe0--angry-mirzakhani-365cef.netlify.com/2019/
> update: redirects to forced redirects per netlify breaking change

- src/components/layout.js
[Jira SC 817](https://sparkbox.atlassian.net/browse/SC-817)
From what I could tell, `og:image` tag needs to be an absolute URL in order for twitter to recognize the image.
To validate: Insert [Netfily Preview URL](https://5e7a4885287d41079732e6ea--angry-mirzakhani-365cef.netlify.com/2019/) into https://cards-dev.twitter.com/validator and ensure the image appears
Preview URL: https://5e7a4885287d41079732e6ea--angry-mirzakhani-365cef.netlify.com/2019/
> fix: og:image path absolute so twitter can read

- gatsby-config.js
- package-lock.json
This work updates the `options.endpoint` url in the `gatsby-config` file. We were previously using an old/incorrect url that 1) caused users that had never signed up before to get a message incorrectly stating that they *had* signed up before and 2) prevented their email from being added to the proper list in Mailchimp. 
To implement this fix, I followed the documentation for `gatsby-plugin-mailchimp`, which we are using, found here: [https://www.gatsbyjs.org/packages/gatsby-plugin-mailchimp/#mailchimp-endpoint](https://www.gatsbyjs.org/packages/gatsby-plugin-mailchimp/#mailchimp-endpoint)
See Story: [SC-922](https://sparkbox.atlassian.net/browse/SC-922)
1. Make sure all PR Checks have passed (CircleCI, Code Climate, Snyk, etc).
2. Pull down all related branches.
3. Confirm all tests …
> SC-922: Email Signup Bug

- 2018/src/drizzle/patterns/footer/footer.hbs
- 2018/src/drizzle/templates/template.hbs
- src/components/footer.js
- src/pages/404.js
- src/sections/intro.mdx
This PR covers:
- simple copy edits to point to the latest year on both 2018 and 2019 homepages and the 404 page
- removes old industrious address on 2018 and 2019
> 2020 Updates

- 2018/src/drizzle/patterns/content-sections/intro.hbs
- 2018/src/drizzle/patterns/content-sections/next-steps.hbs
- 2018/src/drizzle/patterns/footer/footer.hbs
- 2018/src/drizzle/templates/default.hbs
- src/components/2019/footer.js
- src/components/2019/hero.js
- src/components/2020/footer.js
- src/components/SEO.js
- src/pages/2019.js
- src/scss/2020/components/_site-footer.scss
- src/scss/2020/objects/_layout.scss
- src/scss/2020/utilities/_display.scss
- src/sections/2019/intro.mdx
- src/sections/2019/section-5.mdx
- src/sections/2020/challenges.mdx
- src/sections/2020/conclusion.mdx
- src/sections/2020/intro.mdx
- src/sections/2020/newsletter.mdx
- src/sections/2020/respondents.mdx
This updates all three sites and aims to make three major changes: 
1. Change all references to seesparkbox.com to sparkbox.com 
1. Update any contact page links from the old site to the new site
1. Remove references to 123 Webster St
Also corrected a couple small typos / linter issues. 
Review each change on all sites and test that links work.
> chore: update seesparkbox urls to sparkbox.com

- src/components/2021/quote.js
- src/pages/21-patterns.js
- src/scss/2021/components/_quote.scss
- src/scss/2021/tools/_type.scss
- src/sections/2021/section-5.js
This fixes some issues that cropped up after making some changes to the `<Quote />` React component.
The first addresses the missing, and necessary, stroke from the content:
The second addresses the type formatting. The component assumes a generic `<p>` element, but will not override specific classes added to it. However, the component accepts a an attribute called `sizeFormat` which can be set to `small` or `large` and will adjust the default style of the `<p>` element accordingly:
Lastly, when a quote starts with a `<em>` the rust color of the text and the quote decoration clash. To provide an alternative, there is a new attribute called `decoStyle`, which can be set to `alt` which will change the stroke on the left double quote to Neutral 03 at 50% opacity:
The first addresses the …
> DES-48  2021 quote fix

- src/pages/21-patterns.js
- src/scss/2021/components/_pie-chart.scss
Both of these issues were CSS related.
I can’t say 100% what is causing this visual issue, but it seem like the diagonal rendering was causing visual issues with the rendering of the border. To fix this I added in a case that when the diagonal is used, to add a bit more to the box-shadow size to account for this issue.
This is a result of missing default CSS Custom Property values. All the props for the slice size, represented with `--slice-X` should start off with a value of `0`. That has been added to the CSS to correct this issue.
See the /21-patterns page components for reference.
> DES-50 & DES-51: Add PieChart styles to account for edge cases

- src/components/2021/grid-cell.js
- src/scss/2021/base.scss
- src/scss/2021/settings/_variables.scss
This adds in the support for `className` attribute on the `<GridCell>` component (it already existed for `<Grid>`. To add a class name to a grid or cell, a `className` attribute with desired classname from the Sparkle spacing system, like so:
```
<GridCell spanLG="6" className="util-margin-top-1xl">
```
Once this is in place, feel free to adjust the name and values of the `$spacer` map in the `src/scss/2021/settings/_variables.scss` file.
> DES-32: Setup Spacing System

- src/scss/2021/components/_figure.scss
- src/scss/2021/tools/_type.scss
- src/sections/2021/section-1.js
- src/sections/2021/section-2.js
- src/sections/2021/section-3.js
- src/sections/2021/section-4.js
- src/sections/2021/section-5.js
Addresses a bug where the figure caption number would wrap to two lines if the text was long, causing "fig" to be on one line and the number (like "3.2") to be on the next line.
This also addresses a few other bugs I found around figure captions:
- Change the color of figure caption text to pass A11y guidelines for color contrast.
- Add space between a chart and the caption.
- Add missing labels for "responses" numbers.
- Add non-breaking spaces to long captions to minimize awkward line breaks.
> DES-49: Figure text wrap bug

- src/components/2021/figure.js
- src/scss/2021/components/_figure.scss
- Modifier classes `--left` & `--right` to specify the `direction` of the caption. 
- `direction` has a default of `--right`
`cmp-figure__caption--right`
`cmp-figure__caption--left`
> DES-46:  Modifier to swap the figure number and caption

- src/components/2021/bar-chart-table.js
- src/components/2021/bar-chart.js
- src/components/2021/stacked-chart-table.js
- src/components/2021/stacked-chart.js
This work adds a visually hidden table of the bar and stacked bar charts for an improved screen reader experience.
The tables are not visible, so verifying them will need to be done by viewing the source or disabling the styles.
Additionally, this applies an `aria-hidden` to elements of the bar and stacked that the table is meant to replace for screen readers.
> DES-35:  Accessibility Tables

- src/pages/2021.js
Quick Fix: 
The site footer is updated to be contained within a `<div>`
> Des 59  footer div

- src/components/2021/bar-chart-table.js
- src/components/2021/bar-chart.js
- src/components/2021/stacked-chart-table.js
- src/components/2021/stacked-chart.js
Applies React’s `dangerouslySetInnerHTML` to render the HTML properly
> DES-38: Render HTML in chart data

- src/components/2021/intro.js
- Changes the `cmp-intro` `div`  to a `header` element
- Adds a `div` around the two elements containing the title “2021 Design Systems Survey” with an `aria-hidden="true"` 
- Adds a visibly hidden `h1` element with the text “The 2021 Design Systems Survey by Sparkbox”
> DES-61:  heading one markup

- src/scss/2021/components/_intro.scss
Adjust font sizes of the main hero text to make it larger on mobile.
- Open the deploy for this PR https://deploy-preview-292--angry-mirzakhani-365cef.netlify.app/2021/
- Verify that the font sizes for the hero text "2021 Design System Survey" is larger on mobile and tablet screen sizes but the same on desktop.
> DES 72: Mobile hero font size

- src/scss/2021/components/_fixed-sides.scss
Remove a CSS transform in IE 11 to fix a layout issue.
- Open the deploy of this PR. https://deploy-preview-293--angry-mirzakhani-365cef.netlify.app/2021/
- Verify that nothing broke in a modern browser (Chrome, Firefox, or Safari). In particular, the fixed position Sparkbox logo that displays in the top left corner of the viewport.
- Verify that the fixed position Sparkbox logo is not covering up body content in IE11.
> DES 77:  IE 11 logo

- src/pages/2021.js
Remove an unused font file that was being pre-loaded and throwing an error.
This does _not_ fix all of the warning messages but we determined this would be a good fix for now and we can ignore the remaining warnings since they are not breaking anything and there doesn't seem to be an obvious, quick fix.
- Open the PR deploy
- Verify that there is no warning in the console in Chrome or Firefox that says something like " a certain resource was preloaded but not used within a few seconds of the window's load event"
- NOTE these messages will likely still display in Safari but we are saying that is a "won't fix." This PR specifically removes the font that was listed with a warning message for being pre-loaded so that should not be displayed in any browser.
This is what we were seeing before …
> DES-76: Safari warning

- src/pages/2021.js
- src/scss/2021/components/_checkbox.scss
- src/scss/2021/components/_form.scss
- Add dark mode colors to checkboxes and the main CTA icon.
- Add transition values to the text input.
- Open the deploy of this PR https://deploy-preview-291--angry-mirzakhani-365cef.netlify.app/2021
- Scroll to the main CTA at the bottom of the 2021 page.
- Verify that the checkbox inputs and the mail icon look correct compared to the [design](https://www.figma.com/proto/8qXWkVZG2BWmB29tZ320Hs/2021-DS-Survey?page-id=1%3A129&node-id=123%3A3&viewport=1426%2C2807%2C1&scaling=scale-down-width&hide-ui=1).
- Switch your computer to "dark mode" and again, verify that the checkbox and mail icon display in the same way but with reversed colors. You can do this on Mac by opening command center and clicking on "display"
> DES-73: Dark mode colors

- src/components/2021/stacked-chart-table.js
- src/sections/2021/section-3.js
Stacked Bar Charts generate the correct amount of table data rows.
**Run the HTML through the through the [W3C Validator](https://validator.w3.org/) to ensure that none of the following errors exist**: 
Warning: A table row was 5 columns wide, which is less than the column count established by the first row (6).
From line 1, column 79380; to line 1, column 79384
`-->%</td></tr><tr><t`
Warning: A table row was 4 columns wide, which is less than the column count established by the first row (6).
From line 1, column 79490; to line 1, column 79494
`-->%</td></tr><tr><t`
Warning: A table row was 3 columns wide, which is less than the column count established by the first row (4).
From line 1, column 90242; to line 1, column 90246
`-->%</td></tr><tr><t`
Warning: A table row was 3 columns wide, …
> DES-65:  a11y tables

- src/sections/2021/section-1.js
- src/sections/2021/section-2.js
- src/sections/2021/section-3.js
- src/sections/2021/section-4.js
- src/sections/2021/section-5.js
There are instances where bar chart figure captions appear to be floating on their own due to the arrangement of the chart.
Like so.. 
Each of the instances for the bar chart captions has been aligned to the left instead. 
Open the deploy for this PR: https://deploy-preview-297--angry-mirzakhani-365cef.netlify.app/2021/
Review the entire page to make sure that there are no instances where the figure for a barchart appears to be floating on its own.
> DES-74: left align bar chart fig cap

- src/components/2021/figure.js
Render HTML in figure caption
use `<strong>` or `<em>` within a figure caption to make sure that HTML is rendered correctly
> DES-78:  figcaption render html

- src/sections/2021/section-1.js
- src/sections/2021/section-3.js
- src/sections/2021/section-4.js
**DES-79**
- Add spaces around em dashes that appear in the monospace font to help them appear more like em dashes. This was approved by Kaitlyn.
**DES-80**
- This chart title should have red on “employed” like "How many people are employed by your organization?"
> DES 79 & 80: em dashes

- src/sections/2021/section-3.js
Make all sub-section scorecards the same width.
Visually, there might not be much of a difference but you should see that figures 3.4, 3.7, and 3.13 all have the same grid layout properties now.
> DES 89: Scorecard placement

- src/sections/2021/section-3.js
The following paragraphs have been formatted 
- That first paragraph should have that box formatting around it like this
- The 2nd and 3rd should be like this
> DES-94 : format paragraphs

- src/sections/2021/section-3.js
This adds the `&shy;` special character to the word ** Contributors**. Because of how `&shy;` works, a `<br />` was also added to force a two-line presentation of the content.
> DES-98: Fix overflowing content

- src/sections/2021/section-1.js
- src/sections/2021/section-2.js
- src/sections/2021/section-3.js
- src/sections/2021/section-4.js
There were several instances of `<h2>` that followed after the main section heading level 2. 
- I updated all of the instances of extra `<h2>`'s to be an `<h3>` 
This corrected the issue of the `<h4>` following immediately behind the `<h2>`. The `<h2>` has been changed to an `<h3>`
Now there should only be one `<h2>` per section.
> DES-103:  semantic headings

- src/components/2021/bar-chart.js
- src/components/2021/pie-chart.js
- src/components/2021/section-header.js
- src/components/2021/stacked-chart.js
- src/scss/2021/components/_section-header.scss
Resolves the following bugs:
- Charts need to have the heading set to `aria-hidden="true"` as the table caption is what provides this information.
- Section Heading numbers (outlined large number) needs set to `aria-hidden="true"`
- Open the PR deploy
- Use voiceover to ensure that there are no duplicated headings on charts and that the section header text reads correctly
- Ensure nothing broke on the page with the changes to the section header component.
> DES 105: aria hidden fixes

- src/sections/2021/section-4.js
This removes the custom set span values and leaves the default span of 4 columns.
> DES-107:  Fig 4.1 Small Screen Layout

- src/sections/2021/section-3.js
The spacing for the first subsection within section 3 had more spacing than other subsections. 
- Quick fix to remove that extra margin-bottom so that each section's spacing is consistent. 
Each sub section heading should have equal spacing on mobile and desktop.
> DES-104:  Section 3 Heading Spacing

- src/sections/2021/section-1.js
- src/sections/2021/section-2.js
- src/sections/2021/section-3.js
- src/sections/2021/section-4.js
- Updates all areas where horizontal divider lines above chart headings are missing
I found 6 instances, and excluded horizontal lines from above sub header sections in section 3.
> feat: add horizontal divider lines above chart headings

- src/scss/2020/components/_site-header.scss
- src/sections/2020/intro.mdx
- static/_redirects
- Update 2020 to have a link to designsystemssurvey.seesparkbox.com
- Update static/_redirects to redirect / to /2021 so 2021 becomes the new default page
> DES: pre launch

- package-lock.json
- package.json
- src/components/2021/intro.js
- src/scss/2021/components/_intro.scss
- src/scss/2021/utilities/_display.scss
- src/sections/2021/section-3.js
This does two things:
1. The intro animation was setup to require JS in order to do what the CSS property `animation-fill-mode: forwards;` accomplishes. So, the JS requirements were removed and the CSS property added.
2. The second thing has to do with the display of the Priority/Challenge headings as the screen sizes changes. Which does two things as well: The first is that is makes them all consistent, as the first on of these groups was wider. The second thing is it adds some alignment HTML to better handle wrapping. See the following screenshots:
> fix: JS Animation and Section 3 layout

- src/pages/2020.js
- src/pages/2021.js
- src/scss/2020/generic/_fonts.scss
- src/scss/2021/generic/_fonts.scss
This work updates the 2020 and 2021 pages to load fonts from assets.sparkbox.com instead of locally-hosted.
After this is tested, working, and merged we will scrub the repo of the necessary locally-hosted fonts.
For the Sparkboxer reviewing this PR, it is dependent on this PR: https://github.com/sparkbox/public_assets/pull/6
> Load Fonts from assets.sparkbox.com

- README.md
On my M1 Mac, running `npm install` wasn't completing successfully, and showed the error "Prebuilt libvips binaries not yet available for darwin-arm64v8" -- running `brew reinstall vips` according to https://github.com/lovell/sharp/issues/2460#issuecomment-751491241 worked to install vips natively with all its dependencies on Apple Silicon M1.
> Update install docs for M1 Macs

- src/components/2022/circle.js
- src/components/2022/grid-cell.js
- src/components/2022/key-finding.js
- src/components/2022/layout.js
- src/components/2022/quote.js
- src/components/2022/related-reading.js
- src/components/2022/toc-link.js
- src/scss/2022/components/_gauge.scss
- src/scss/2022/components/_hero.scss
- src/scss/2022/components/_key-finding.scss
- src/scss/2022/components/_number.scss
- src/scss/2022/components/_section-header.scss
- src/scss/2022/components/_toc-link.scss
- src/scss/2022/generic/_normalize.scss
- src/scss/2022/objects/_grid.scss
- src/scss/2022/objects/_limiters.scss
- src/scss/2022/settings/_font-size.scss
- src/scss/2022/settings/_root.scss
- src/sections/2022/intro.mdx
- src/sections/2022/section-1.mdx
- src/sections/2022/section-2.mdx
- src/sections/2022/section-3.mdx
- src/sections/2022/section-4.mdx
- src/sections/2022/section-5.mdx
- src/sections/2022/table-of-contents.mdx
Addresses many responsive layout and sizing issues from smallest (appx 320px or 20rem) on up to the largest breakpoint (80rem). The primary concer is that content is legible. Please review by resizing the browser with the inspector open in order to get the width down to 320ish pixels, the slowly expand the browser width up, around 400pixels or more you can close the inspector and continue from that size up to at least 1280 or above.
**PLEASE Do Not Use Responsive Mode!**
Responsive mode is neat feature of browsers to mimic different devices sizes but there are two fundamental problems that make the bad for testing:
1. Responsive mode does not show the in between screen sizes that make RWD so beneficial.
2. They often require applying an artificial zoom to the page to fit the emulated …
> [7] 2022/responsive fixes
