sparkbox/designsystemssurvey

package-lock.json
src/drizzle/patterns/footer/footer.hbs

fix: urls http to https

---

src/pages/page-2.js
src/scss/_elements.lists.scss
src/scss/_settings.variables.colors.scss
src/scss/base.scss

Add list styles
Note: The JIRA card associated with this card is for body copy styles. There is a WIP PR for a body copy mixin, therefore I only created the list styles in this PR.
In you local dev environment, go to http://localhost:8000/page-2/ to see the list styles.
JIRA: [DSS-48](https://sparkbox.atlassian.net/browse/DSS-48)
InVision [design comps](https://sparkbox.invisionapp.com/d/main#/console/17598448/365064738/preview)

DDS-48 : add list styles

---

src/scss/_elements.text.scss
src/scss/_settings.variables.colors.scss
src/scss/base.scss

Add link styles
JIRA: [DSS-42](https://sparkbox.atlassian.net/browse/DSS-42)
InVision [design comps](https://sparkbox.invisionapp.com/d/main#/console/17598448/365064738/preview)

DSS-42 :  add link styles

---

src/components/layout.js
src/pages/index.js
src/pages/page-2.js
src/scss/_components.intro.scss
src/scss/_elements.layout.scss
src/scss/_elements.lists.scss
src/scss/_settings.variables.colors.scss
src/scss/base.scss

Add Intro block
In you local dev environment, go to http://localhost:8000/.
Note that I've moved the typography styles to http://localhost:8000/page-2/ for reference. I've also commented out the Gatsby header and image from the layout. I left them as a reference. We can remove them now or later.
I also made an adjustment to the list styles.
JIRA: [DSS-41](https://sparkbox.atlassian.net/browse/DSS-41)
InVision [design comps](https://sparkbox.invisionapp.com/d/main#/console/17598448/365064738/preview)

DSS-41 : Add Intro block

---

src/pages/page-2.js
src/scss/_tools.typography.scss

Add diagram text style with triple border [DSS-52](https://sparkbox.atlassian.net/browse/DSS-52)
To test, look at it on localhost:8000

DSS-52 feat: add diagram text style

---

gatsby-config.js
package-lock.json
package.json

Add basic auth with the gatsby-plugin-netlify plugin.
To test: Go to [this PR's Netlify preview](https://5cef130288ca62000907793c--angry-mirzakhani-365cef.netlify.com/) and make sure it prompts for a username and password. This info is in 1Password (search for design system survey).

feat: basic auth with netlify header plugin

---

gatsby-config.js
package-lock.json
package.json
src/components/layout.js
src/pages/index.js
src/scss/_elements.layout.scss
src/scss/_settings.variables.fonts.scss
src/scss/base.scss
src/sections/intro.mdx
src/sections/section-1.mdx
src/sections/section-2.mdx
src/sections/section-3.mdx
src/sections/section-4.mdx
src/sections/section-5.mdx

[DSS-61](https://sparkbox.atlassian.net/browse/DSS-61)
- This pulls in all the content from the Write-up. 
- Adds in MDX (a Markdown plugin for Gatsby)
- Content that will use extra Components are marked.

DSS-61: Add content from write-up

---

src/pages/page-2.js
src/scss/_components.intro.scss
src/scss/_components.typography.scss
src/scss/_elements.text.scss
src/scss/_settings.variables.colors.scss
src/scss/_tools.mixins.general.scss
src/scss/_tools.typography.scss
src/scss/base.scss

* refactor existing text style names
* add secondary heading text style
* add yellow to color vars for gradient
* add mixin, class for style
* add style example to page 2
* add comments to typography to make it more accessible for devs
To test, check page two and see that all the text styles are still working and match the design

DSS-50 new header style, refactor existing styles

---

src/pages/page-2.js
src/scss/_elements.lists.scss
src/scss/_elements.text.scss
src/scss/_utilities.text.scss
src/scss/base.scss

List number styles already existed in `_elements.lists.scss`. This adds styles for `<mark>` and utility classes for bold and italic font.

feat: numbered list styles

---

src/components/table-of-contents.js
src/pages/index.js
src/scss/_components.table-of-contents.scss
src/scss/_settings.variables.breakpoints.scss
src/scss/base.scss

* add toc to base.scss
* remove .scss extension from other imports in base.scss
* create toc component
* add component to index
* adjust breakpoints (didn't end up using these, but the changes still make sense for future proofing)
Look at index page locally at localhost:8000. Card needs chiseling work, recommendations appreciated.

DSS-45 feat: toc component

---

src/components/content-block.js
src/components/header-block.js
src/components/table-of-contents.js
src/components/top-features.js
src/pages/index.js
src/scss/_components.percentage-list.scss
src/scss/_components.table-of-contents.scss
src/scss/_components.typography.scss
src/scss/_elements.layout.scss
src/scss/_elements.lists.scss
src/scss/_elements.table.scss
src/scss/_elements.text.scss
src/scss/_objects.layout.max-width.scss
src/scss/_settings.variables.max-width.scss
src/scss/base.scss
src/sections/section-1.mdx
src/sections/section-2.mdx
src/sections/section-3.mdx
src/sections/section-4.mdx
src/sections/section-5.mdx

* Classes for overall, headers, content width
* Variables for widths
* Element styles for header, p widths

feat: layout styles for width

---

package-lock.json
package.json
src/components/diagram-2a-chart-card.js
src/components/diagram-2a-chart.js
src/components/diagram-2a-table.js
src/components/diagram-3a-table.js
src/components/diagram-3b-table.js
src/components/diagram-3c-table.js
src/components/diagram-4a-table.js
src/components/diagram-4b-table.js
src/components/layout.js
src/components/table-of-contents.js
src/components/top-features.js
src/js/chart-animation.js
src/pages/chart.mdx
src/scss/_components.diagram.chart.scss
src/scss/_elements.root.scss
src/scss/_settings.variables.colors.scss
src/scss/_utilities.scss
src/scss/base.scss
src/sections/section-2.mdx

[DSS-55](https://sparkbox.atlassian.net/browse/DSS-55)
* Fix console warnings/errors
* Create responsive chart component and styles
* Create reusable, on-scroll animation

DSS-55 vertical chart 2a

---

src/components/table-of-contents.js
src/pages/index.js
src/scss/_components.skip-link.scss
src/scss/base.scss

Add skip to table of contents link when tabbing

DSS-19 skip to TOC

---

src/components/diagram-2a-chart-card.js
src/components/diagram-2a-chart.js
src/components/top-features.js
src/scss/_components.diagram.chart.scss
src/scss/_components.table-of-contents.scss
src/scss/_components.typography.scss

* fix: table of contents overlapping in ie11
* fix: text-underline to none for ie
* fix: add max-width to top features
* refactor: vertical chart, include fallbacks for ie11
* fix: vertical chart value alignment in Edge

DSS-74 ie11 bugs, chart refactor

---

2018/src/drizzle/templates/template.hbs
2018/src/scss/_components.latest-link.scss
2018/src/scss/base.scss

Steps to test:
1. Run `npm run build2018`
2. Run `gatsby build`
3. Run `gatsby serve`
4. Navigate to `/2018` in your browser

DSS-57: Add link to latest survey

---

package.json
src/components/diagram-2a.js
src/components/diagram-3b.js
src/components/diagram-3c.js
src/components/diagram-table-block.js
src/scss/_components.diagram.chart.scss
src/scss/_components.diagram.scss
src/sections/section-2.mdx
tasks/comments.js

* Add HTML conditional comments to handle charts in IE9 (hides charts, uses tables)
* Refactor charts to work in IE10 with flexbox
Tested in modern Chrome, Firefox, Safari, Edge, and IE9-11

DSS-75 add comments for IE9, refactor charts for IE10-11

---

src/components/form.js
src/scss/_components.form.scss

Adds styles for fail and success form submission messages.

feat: Add form submission success/fail message styles

---

src/components/form.js
src/scss/_components.form.scss

Removes "query" in Firefox, IE browsers. Adds compatibility with IE9.

DSS-83 fix: form bugs

---

src/components/diagram-2a.js
src/components/diagram-3a.js
src/components/diagram-3b.js
src/components/diagram-3c.js
src/components/diagram-4a.js
src/components/diagram-4b.js

Aligns with changes made in [write-up doc](https://docs.google.com/document/d/1u86wlc3KZcq2_GJCnYWIt6kWw1RelSyh9HWEYXURacA/edit?ts=5cd9db30#)

DSS-84 fix: copy for diagram descriptions

---

src/components/form.js
src/scss/_components.form.scss

* Refactor label to surround input
* Refactor label message to clarify that it's asking for an email
address

DSS-92 fix: voiceover form sending user to top of site

---

src/components/diagram-4a.js
src/components/diagram-table-block.js
src/pages/404.js

Fixes all the linting errors that were appearing in the command line and console when running `gatsby develop`.

DSS-99 fix: linting errors

---

src/scss/_components.diagram.scss

Test: check that we have charts in IE9

DSS-112 fix: charts to show in ie9

---

src/components/diagram-3b.js
src/components/table-of-contents.js
src/components/top-features-elements.js
src/components/top-features-tools.js
src/sections/intro.mdx
src/sections/section-1.mdx
src/sections/section-2.mdx
src/sections/section-3.mdx
src/sections/section-4.mdx
src/sections/section-5.mdx

[DSS-116](https://sparkbox.atlassian.net/browse/DSS-116)
Implement requested copy updates from the [DS Survey Content Changes Google doc](https://docs.google.com/document/d/1eOYSGpDBc6MtfjPfYQPgV_ukexVG2bixk9tEtY8ALzg/edit#)
Reference the [2019 Design Systems Survey Google doc](https://docs.google.com/document/d/1u86wlc3KZcq2_GJCnYWIt6kWw1RelSyh9HWEYXURacA/edit#) as needed.
- _Note that h2's and h3's in this Google doc are implemented as h3's and h4's on the design system survey site._

DSS-116 :  Copy updates

---

src/components/callout-link.js
src/components/link-item.js
src/components/link-list.js
src/scss/_components.link-list.scss
src/scss/_components.typography.scss
src/scss/base.scss
src/sections/section-3.mdx
src/sections/section-5.mdx

Adds a link list of foundry articles to Section 5

feat: Create Foundry article list component

---

src/sections/section-5.mdx

Should cover everything that's published since Julie's article. 
Please confirm order and items off this list: https://seesparkbox.com/foundry/category/design_systems

Add more articles

---

src/sections/intro.mdx

Adds in the 2020 survey link at the top of the intro section (just below the hero).

feat: Add link to 2020 survey

---

2018/src/drizzle/patterns/footer/footer.hbs
src/components/footer.js

Email, Phone, Address - should be what you see for the contact information now on 2018 and 2019

more consistent contact titles

---

src/components/2021/svg-arrow.js
src/scss/2021/components/_bar-chart.scss
src/scss/2021/components/_fixed-sides.scss
src/scss/2021/components/_pie-chart.scss
src/scss/2021/components/_stacked-chart.scss
src/scss/2021/objects/_layout.scss
src/scss/2021/settings/_variables.scss

A few small enhancements. See commit messages for descriptions of changes.
I haven't reviewed in anything but Chrome 😬 forgive me

DES-19: Small enhancements

---

src/sections/2021/section-6.mdx

Adds content for section 6. Reviewed in Chrome, Sarafi, and Firefox.

Feat: Add Section 6

---

src/components/2021/bar-chart.js
src/sections/2021/section-3.js
src/sections/2021/section-4.js
src/sections/2021/section-5.js

- bar chart supports a single data type
- bar charts with a single data type do not need a `keyMap`
- compare bar charts with single data types to bar charts with multiple data types

DES-45: Fix bar chart 

---

src/components/2021/table-index.js
src/pages/2021.js
src/scss/2021/elements/_hr.scss
src/scss/2021/elements/_root.scss
src/scss/2021/settings/_variables.scss
src/sections/2021/section-1.js
src/sections/2021/section-2.js
src/sections/2021/section-3.js

Adds spacing and layout grid properties for all content from the hero through section 3. I'm calling this a first pass at getting the layout right and we can adjust as needed once the scorecard component is done and we have time to review everything all together.
For now I focused on getting the layout to look as close to the design as possible and it went well! There are a few differences but nothing that feels like a loss to me. The flexible grid and spacing systems are really really helpful.
Fair warning, I have not browser tested.

DES-53: Content in Grid Layout (hero through section 3)

---

package-lock.json
package.json
src/components/2021/number.js
src/components/2021/scorecard.js
src/scss/2021/base.scss
src/scss/2021/components/_number.scss
src/scss/2021/components/_scorecard.scss
src/scss/2021/elements/_root.scss
src/scss/2021/settings/_variables.scss
src/sections/2021/section-1.js
src/sections/2021/section-2.js
src/sections/2021/section-3.js
src/sections/2021/section-4.js

This work introduces several new components for creating the scorecard visual style.

DES-16: Scorecard and Number Styles

---

src/components/2021/figure.js
src/scss/2021/components/_section-header.scss
src/sections/2021/section-1.js
src/sections/2021/section-2.js
src/sections/2021/section-3.js
src/sections/2021/section-4.js
src/sections/2021/section-5.js
src/sections/2021/section-6.js

- Add grid layout and spacing styles to sections 4-6.
- Adjust font sizes in the section headers.
- Cleanup various grid spacing across the page.

DES 55: Content in grid and spacing (sections 4 - 6)

---

src/components/2021/number.js
src/components/2021/table-of-contents.js
src/scss/2021/components/_back-to-top.scss
src/scss/2021/components/_button.scss
src/scss/2021/components/_cta.scss
src/scss/2021/components/_footer.scss
src/scss/2021/components/_toc.scss
src/scss/2021/elements/_a.scss
src/scss/2021/elements/_root.scss
src/scss/2021/generic/_fonts.scss
src/scss/2021/settings/_variables.scss
src/scss/2021/tools/_type.scss

- Add hover states to all <a> tags in various components
- Remove hex code colors from the footer component
- Adjust the font weight of body copy
- Adjust the min font size of scorecard number text

DES-32: Add hover states for all links

---

src/components/2021/bar-chart.js
src/components/2021/stacked-chart.js
src/scss/2021/components/_bar-chart.scss
src/scss/2021/components/_stacked-chart.scss
src/scss/2021/settings/_variables.scss

Implementation for how a bar chart and stacked chart value moves outside the container

DES-33:  small bar chart value

---

src/components/2021/table-index.js
src/pages/2021.js
src/scss/2021/base.scss
src/scss/2021/components/_skip-link.scss

1. Skip to Menu - which goes to the section link list
2. Skip to Content - which goes to section 1

DES-34: skip links

---

src/components/2021/contact-form.js
src/pages/2021.js
src/pages/21-patterns.js
src/scss/2021/base.scss
src/scss/2021/components/_checkbox.scss
src/scss/2021/components/_cta.scss
src/scss/2021/components/_type.scss

- Add styles for the checbox input
- Adjust the layout of the main CTA on the page to reflect the design

DES-29: Add checkbox input styles

---

src/pages/404.js
src/scss/2021/base.scss
src/scss/2021/components/_page-not-found.scss
src/scss/2021/utilities/_display.scss

DES-36:  404 Page

---

src/components/2021/art-element.js
src/components/2021/intro.js
src/components/2021/layout.js
src/components/2021/table-index.js
src/scss/2021/_manifest.scss
src/scss/2021/components/_art-element.scss
src/scss/2021/components/_intro.scss
src/scss/2021/generic/_normalize.scss
src/scss/2021/objects/_layout.scss
src/sections/2021/section-1.js
src/sections/2021/section-2.js
src/sections/2021/section-3.js
src/sections/2021/section-4.js
src/sections/2021/section-5.js
src/sections/2021/section-6.js

- Add a new component that supports rendering three different SVG "art elements" which are decorative additions to the content.
- Adds these new art elements to the page according to the design with some changes based on how content flows on the real page.
- Adjusts some of the grid layout on the page.

Des 23: Add art elements

---

src/components/2021/contact-form.js
src/scss/2021/_manifest.scss
src/scss/2021/components/_form.scss
src/scss/2021/settings/_sparkle.scss

DES-30: Text Input

---

src/components/2021/table-index.js

- Table of contents is wrapped in a `nav` element.

DES-66:  Nav Wrap

---

src/components/2021/table-of-contents.js

- moves `aria-label` to anchor tag
- `aria-label` is set to Section [Number]: [Section Title]

DES-64: move aria label to anchor tag

---

src/sections/2021/section-1.js
src/sections/2021/section-2.js
src/sections/2021/section-3.js
src/sections/2021/section-4.js
src/sections/2021/section-5.js
src/sections/2021/section-6.js

Covers all the edits from the doc: https://docs.google.com/document/d/1WDHPWh94f3lguXFZePKWm8NZTkgJ1BA0r2ztzXoNBGI/edit#heading=h.z1a5xpzcw865
Section 1: Delete this text “In house respondents to to work at larger organizations, while agency respondents work primarily at smaller companies.”

Copy Edits

---

src/pages/2021.js
src/scss/2021/components/_figure.scss
src/scss/2021/components/_quote.scss
src/scss/2021/settings/_variables.scss
src/scss/2021/tools/_type.scss
src/sections/2021/section-1.js
src/sections/2021/section-2.js
src/sections/2021/section-3.js
src/sections/2021/section-4.js
src/sections/2021/section-5.js
src/sections/2021/section-6.js

- Left align caption text that is positioned on the left.
- Decrease the size of caption text to help it fit better.
- Increase space between elements on the page using existing spacing classes.
- Open the deploy branch of the PR.
- View the 2021 page on phone, tablet, and desktop screen sizes.
- Review to ensure the layout is evenly spaced and nothing looks "broken"

DES 67: Vertical Spacing

---

src/sections/2021/section-3.js

- The title should be “Priorities & Challenges” to match the ampersand in the other title/TOC
- In Figure 3.5, add quotation marks at the end of: “What are the top challenges your design system team is facing at this moment?"
- Section 3.2: the quote has a 2nd dash
- The “Not successful” line, the 17% should be the style of “They often or always contribute to the design system (4–5)”
- Mislabeled Figure 3.11 should be 3.15
- Mislabeled Figure 1.14 should be 3.14

Section 3 updates

---

src/sections/2021/section-2.js

- In Figure 2.2, drop “An” and capitalize “Individual”: “An individual contributor(s) suggested starting a design system” to: “Individual contributor(s) suggested starting a design system”
- Under Fig 2.4, the 2 paragraphs of text should be the subtitle formatting like the “Responses:” text since it applies to the chart
- First pie chart should be “Fig 2.1” not “1.1”
- Intro paragraph adds “in-house” to be “Let’s learn more about the commonalities across our in-house respondents’ design systems.”

Section 2 Updates

---

src/scss/2021/components/_bar-chart.scss
src/scss/2021/components/_number.scss
src/scss/2021/components/_pie-chart.scss
src/scss/2021/components/_quote.scss
src/scss/2021/components/_slim-heading.scss
src/scss/2021/components/_stacked-chart.scss
src/scss/2021/settings/_variables.scss
src/scss/2021/tools/_type.scss

DES-81: Font Sizes

---

src/components/2021/footer.js

- All links in the footer should go to proper web pages.

DES-93:  footer links

---

src/components/2021/contact-form-error.js
src/components/2021/contact-form-sent.js
src/components/2021/contact-form.js
src/js/2021/form-submit.js
src/pages/2021.js
src/scss/2021/_manifest.scss
src/scss/2021/components/_checkbox.scss
src/scss/2021/components/_cta.scss
src/scss/2021/components/_form-field.scss
src/scss/2021/components/_form.scss
src/scss/2021/elements/_root.scss
src/scss/2021/utilities/_colors.scss

[DES-58 on Jira](https://sparkbox.atlassian.net/browse/DES-58)
There are several moving pieces with this and I’m no 100% sure how to test for all scenarios, but I can provide what I know we can test. The form submits to Netlify which collects the data and it extracted via Zapier into MailChimp. Processing wise, the heavy lifting is really done by Zapier and not something we can test for this right. That’s only background for what all is happening as part of this work.
Because of this process, we don’t need to hold strictly to MailChimp form naming conventions, so those have been omitted in some places.
1. Go to the [PR Deploy Form][form]
2. Immediately pres the **Submit** button without modifying the form
3. Verify errors messages for the checkbox group, the name, and the email
1. Go to …

DES-58: Functioning Form

---

src/sections/2021/section-6.js

Emily mentioned that the text formatting is fine: https://sparkbox.slack.com/archives/CF59681QA/p1625752719119100?thread_ts=1625752004.116800&cid=CF59681QA
- Reduce spacing between paragraphs in the conclusion

Conclusion formatting

---

src/scss/2021/components/_scorecard.scss

- Additional padding between each of the score card items on small screens

DES-106: space between columns in Fig 3.3

---

src/components/2021/art-element.js
src/components/2021/bar-chart-table.js
src/components/2021/bar-chart.js
src/components/2021/contact-form-error.js
src/components/2021/contact-form-sent.js
src/components/2021/contact-form.js
src/components/2021/figure.js
src/components/2021/grid-cell.js
src/components/2021/grid.js
src/components/2021/intro.js
src/components/2021/pie-chart.js
src/components/2021/quote.js
src/components/2021/section-header.js
src/components/2021/stacked-chart-table.js
src/components/2021/stacked-chart.js
src/components/2021/svg-arrow.js
src/pages/2021.js
src/pages/21-patterns.js
src/pages/404.js
src/sections/2021/section-1.js
src/sections/2021/section-2.js
src/sections/2021/section-3.js
src/sections/2021/section-4.js
src/sections/2021/section-5.js
src/sections/2021/section-6.js

React formatting to clear out console warnings.
To test:
1. Review the console locally on `feat/2021`
2. Switch to this branch and check the console warnings

DES-112: React housekeeping

---

src/components/2021/fixed-sides.js
src/js/2021/section-observer.js
src/pages/2021.js

Test on https://deploy-preview-315--angry-mirzakhani-365cef.netlify.app/2021/ on several browsers.
The left fixed side middle section with update with the active section.

DES-108: Intersection Observer Section Display

---

src/sections/2021/section-6.js

- Updates to body copy in the conclusion

DES-113:  copy updates to conclusion

---

src/components/2021/contact-form-sent.js
src/sections/2021/section-3.js
src/sections/2021/section-5.js

Add a link on all CTA buttons for “Take the Assessment”: 
- Links are included in Sections 3, 5, and within the contact form after submission. 
https://1o5dmry8dy0.typeform.com/to/m1PuXyVL?utm_campaign=dssurvey

DES-100: add assessment links

---

src/components/2021/contact-form.js
src/js/2021/form-submit.js

Ok. This adds some additional checks to or form validation **and** clears out the messages on a resubmit attempt.
Be sure to use this form when testing: https://deploy-preview-321--angry-mirzakhani-365cef.netlify.app/2021/
The big thing is to try submitting the form various ways but 3 are most important:
1. Email field blank (should error)
2. Email field with `email@example` (should error)
3. Email field with `email@example.com`  (should pass)

DES-114: Add checks for email formatting

---

package-lock.json
package.json
src/components/2021/art-element.js
src/components/2021/intro.js
src/scss/2021/components/_intro.scss
src/scss/2021/settings/_variables.scss

- Add animation to the homepage hero text and art element
- Open the PR deploy.
- Ensure the animation appears consistent across devices and screen sizes.
- Ensure the content still loads without JS.

DES-53: Homepage hero animation

---

src/components/2022/grid-cell.js
src/components/2022/grid.js
src/components/2022/layout.js
src/components/2022/screen-block.js
src/components/2022/toc-link.js
src/pages/2022.js
src/scss/2022/base.scss
src/scss/2022/components/_hero.scss
src/scss/2022/components/toc-link.scss
src/scss/2022/elements/_headings.scss
src/scss/2022/objects/_grid.scss
src/scss/2022/objects/_limiters.scss
src/scss/2022/settings/_font-size.scss
src/scss/2022/settings/_media-queries.scss
src/scss/2022/settings/_root.scss
src/scss/2022/settings/_spacer.scss
src/scss/2022/tools/_media-queries.scss
src/scss/2022/tools/_typography.scss
src/scss/2022/utilities/_colors.scss
src/scss/2022/utilities/_sparkle.scss
src/sections/2022/intro.mdx
src/sections/2022/section-1.mdx
src/sections/2022/section-2.mdx
src/sections/2022/section-3.mdx
src/sections/2022/section-4.mdx
src/sections/2022/section-5.mdx
src/sections/2022/section-6.mdx
src/sections/2022/table-of-contents.mdx

This work setup up the table of contents, the content sections, and the smooth scroll feature.
[Figma Comp](https://www.figma.com/file/VcIuWHbkjExLZ8SNQZipAo/2022-DS-Survey?node-id=2713%3A945)
**Notes:** 
- One known missing piece of this work is the diamond appearing on the hover state. For now this sets up the base styles, sections, and smooth scroll.
- This pulls in the grid system React component from 2021. This approach relies on CSS Custom Properties and while it accommodates small screen not all screen sizes are being tested other than large screen at the moment.
- Design accuracy. The design is still a work in progress with changes coming in the browser as needed. It is more important to check for legibility and aesthetic feel when it comes to design.
- Small screen. There are …

[2] 2022/table of contents
